steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/taiyaki-test1/my-repo/blender-func:latest', '.']
    dir: 'functions'

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/taiyaki-test1/my-repo/blender-func:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'blender-service'
    - '--image'
    - 'us-central1-docker.pkg.dev/taiyaki-test1/my-repo/blender-func:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '1000m'
    - '--timeout'
    - '540s'
    - '--concurrency'
    - '160'
    - '--set-env-vars'
    - 'PORT=8080'

images:
  - 'us-central1-docker.pkg.dev/taiyaki-test1/my-repo/blender-func:latest'

options:
  machineType: 'E2_HIGHCPU_8'
timeout: '3600s'